### ISSUE TITLE
I cant create folder files.Fix it.

### ISSUE THREAD

**Issue by ken640** [SoapboxRaceWorld/GameLauncher_NFSW#119]
- **Launcher Version:** 
- **Operating system:** 
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):**

**Comment by maxside2** [comment]
AYUDA ME SALE ESTO CON LA RECIENTE ACTUALIZACION 

PLEASE CHOOSE A DIFFERENT DIRECTORY FOR THE GAME LAUNCHER.
SPECIAL FOLDERS SUCH AS:
DOWNLOADS DOCUMENTS DESKTOP VIDEOS MUSIC ONEDRIVE OR ANY TYPE OF USER FOLDERS
ARE DISADVISED

**Comment by maxside2** [comment]
AYUDA ME SALE  ESTO CON LA RECIENTE ACTUALIZACION

ELIJA UN DIRECTORIO DIFERENTE PARA EL LANZADOR DEL JUEGO.
CARPETAS ESPECIALES COMO:
DESCARGAS DOCUMENTOS VÍDEOS DE ESCRITORIO MÚSICA ONEDRIVE O CUALQUIER TIPO DE CARPETAS DE USUARIO
SE DESACTIVAN

**Comment by maxside2** [comment]
AYUDA ME SALIO ESTO CON LA RECIENTE ACTUALIZACION

ELIJA UN DIRECTORIO DIFERENTE PARA EL LANZADOR DEL JUEGO.
CARPETAS ESPECIALES COMO:
DESCARGAS DOCUMENTOS VÍDEOS DE ESCRITORIO MÚSICA ONEDRIVE O CUALQUIER TIPO DE CARPETAS DE USUARIO
SE DESACTIVAN

**Comment by x-Ghosts** [comment]
Hello @maxside2  !

The message that you have received recently on the launcher refers to the Launcher files location - directory. Well, the launcher now will not accept the following directories :

(X is the drive that has the OS like C or D, if this last is a primary drive).

X:\Program Files
X:\Program Files (x86)
X:\Users_(ActualAccountonyourpc)_\Downloads
X:\Users_(ActualAccountonyourpc)_\Documents
X:\Users_(ActualAccountonyourpc)_\Desktop
X:\Users_(ActualAccountonyourpc)_\Video
X:\Users_(ActualAccountonyourpc)_\Music
X:\Users_(ActualAccountonyourpc)_\OneDrive
.....
That's why we recommend first to :
1 - Create first of all a folder on your actual drive that has the OS. If *C:* is your actual Drive that contain the OS, create a folder called by : SBRW or SoapBox Race World. Make sure it looks like the image on this link : https://imgur.com/a/mXgccEu.

2 - On that SBRW Folder that you have just created, make sure you create 2 other sub-folders : one goes for the Launcher Files (that you will extract it via the Release.zip) and the other goes for the GameFiles (It will get download via the Launcher).

3 - Extract the Release.zip into the Launcher Folder, and run as Administrator the GameLauncher.exe .
----> Note : It may ask you to download some additional componements, you should let it and accept that, because some important things wasn't installed on you pc.

4 -Once you choose the server, and the launcher will appear on it complete form in front of you. Go on the launcher settings (It looks like a gear icon), then, look for ** Change GameFiles Path**. This step will let you change the GameFiles directory, Make sure you choose The GameFiles folder that you have created it on X:\SBRW. Click on save to save your changes, and restart the Launcher.

I guess, this is the right solution for you. Inform me if it worked for you.
Kind Regards,
Mr.Elite.

**Comment by x-Ghosts** [comment]
Hello @ken640  !

The message that you have received recently on the launcher refers to the Launcher files location - directory. Well, the launcher now will not accept the following directories :

(X is the drive that has the OS like C or D, if this last is a primary drive).

X:\Program Files
X:\Program Files (x86)
X:\Users_(ActualAccountonyourpc)\Downloads
X:\Users(ActualAccountonyourpc)\Documents
X:\Users(ActualAccountonyourpc)\Desktop
X:\Users(ActualAccountonyourpc)\Video
X:\Users(ActualAccountonyourpc)\Music
X:\Users(ActualAccountonyourpc)_\OneDrive
.....
That's why we recommend first to :
1 - Create first of all a folder on your actual drive that has the OS. If C: is your actual Drive that contain the OS, create a folder called by : SBRW or SoapBox Race World. Make sure it looks like the image on this link : https://imgur.com/a/mXgccEu.

2 - On that SBRW Folder that you have just created, make sure you create 2 other sub-folders : one goes for the Launcher Files (that you will extract it via the Release.zip) and the other goes for the GameFiles (It will get download via the Launcher).

3 - Extract the Release.zip into the Launcher Folder, and run as Administrator the GameLauncher.exe .
----> Note : It may ask you to download some additional componements, you should let it and accept that, because some important things wasn't installed on you pc.

4 -Once you choose the server, and the launcher will appear on it complete form in front of you. Go on the launcher settings (It looks like a gear icon), then, look for ** Change GameFiles Path**. This step will let you change the GameFiles directory, Make sure you choose The GameFiles folder that you have created it on X:\SBRW. Click on save to save your changes, and restart the Launcher.

I guess, this is the right solution for you. Inform me if it worked for you.
Kind Regards,
Mr.Elite.

**Comment by maxside2** [comment]
> ¡Hola @ maxside2 !
> 
> El mensaje que ha recibido recientemente en el lanzador se refiere a la ubicación de los archivos del lanzador: directorio. Bueno, el lanzador ahora no aceptará los siguientes directorios:
> 
> (X es la unidad que tiene el SO como C o D, si esta última es una unidad primaria).
> 
> X: \ Archivos de programa
> X: \ Archivos de programa (x86)
> X: \ Users_ (ActualAccountonyourpc) _\ Downloads X: \ Users_ (ActualAccountonyourpc) _\ Documents X: \ Users_ (ActualAccountonyourpc) _\ Desktop X: \ Users_ (ActualAccountonyourpc) _\ Video X : \ Users_ (ActualAccountonyourpc) _\ Music X: \ Users_ (ActualAccountonyourpc) _ \ OneDrive
> .....
> Es por eso que recomendamos primero:
> 1 - Crear en primer lugar una carpeta en su disco real que tenga el sistema operativo. Si _C:_ es su unidad real que contiene el sistema operativo, cree una carpeta llamada por: SBRW o SoapBox Race World. Asegúrese de que se parezca a la imagen de este enlace:https://imgur.com/a/mXgccEu .
> 
> 2 - En esa carpeta SBRW que acaba de crear, asegúrese de crear otras 2 subcarpetas: una va para los Archivos del iniciador (que lo extraerá a través del Release.zip) y la otra va para los GameFiles ( obtener la descarga a través del Lanzador).
> 
> 3 - Extraiga Release.zip en la carpeta Launcher y ejecute como administrador GameLauncher.exe.
> ----> Nota: Es posible que le pida que descargue algunos componentes adicionales, debe dejarlo y aceptarlo, porque algunas cosas importantes no se instalaron en su PC.
> 
> 4 -Una vez que elija el servidor, el lanzador aparecerá en forma completa frente a usted. Vaya a la configuración del iniciador (parece un icono de engranaje), luego, busque ** Cambiar ruta de GameFiles **. Este paso te permitirá cambiar el directorio GameFiles. Asegúrate de elegir la carpeta GameFiles que la has creado en X: \ SBRW. Haga clic en guardar para guardar sus cambios y reinicie el Lanzador.
> 
> Supongo que esta es la solución adecuada para ti. Infórmeme si funcionó para usted.
> Saludos
> cordiales , señor Elite.

Muy agradecido señor elite perfecto todo solucione el problema gracias ahora a correr en neef for speed world : )

**Comment by ken640** [comment]
Hi it worked.Thank you for helping.I had to make backup for my hard drive because i use SSD.Sounds impossible but it worked for me.

**Comment by x-Ghosts** [comment]
No problem ! My pleasure to see having fun on this game !
See ya on the streets among the SBRW servers ! @ken640 @maxside2
