### ISSUE TITLE
Can't run the game launcher

### ISSUE THREAD

**Issue by EXDYahir** [SoapboxRaceWorld/GameLauncher_NFSW#120]
- **Launcher Version:** 2.1.7.1
- **Operating system**: Windows 7 
- **Antivirus/Firewall (if any):** None/Yes 
- **Wine/Mono Version (if any):** 

- Please help me with thist in the the recent update

"PLEASE CHOOSE A DIFFERENT DIRECTORY FOR THE GAME LAUNCHER.
SPECIAL FOLDERS SUCH AS:
PROGRAM FILES OR PROGRAM FILES (X86) DOWNLOADS DOCUMENTS DESKTOP VIDEOS MUSIC ONEDRIVE OR ANY TYPE OF USER FOLDERS
ARE DISADVISED"

**Comment by confite276** [comment]
a mi tambien me sale eso ,F. (spanish)

**Comment by x-Ghosts** [comment]
Hello @EXDYahir !

The message that you have received recently on the launcher refers to the Launcher files location - directory. Well, the launcher now will not accept the following directories : 

(X is the drive that has the OS like C or D, if this last is a primary drive).

- X:\Program Files
- X:\Program Files (x86)
- X:\Users\_(ActualAccountonyourpc)_\Downloads
- X:\Users\_(ActualAccountonyourpc)_\Documents
- X:\Users\_(ActualAccountonyourpc)_\Desktop
- X:\Users\_(ActualAccountonyourpc)_\Video
- X:\Users\_(ActualAccountonyourpc)_\Music
- X:\Users\_(ActualAccountonyourpc)_\OneDrive
.....

That's why we recommend first to :
1 - Create first of all a folder on your actual drive that has the OS. If **C:\** is your actual Drive that contain the OS, create a folder called by : **SBRW** or **SoapBox Race World**. Make sure it looks like the image on this link : **https://imgur.com/a/mXgccEu**.

2 - On that SBRW Folder that you have just created, make sure you create 2 other sub-folders : one goes for the **Launcher Files (that you will extract it via the Release.zip)** and the other goes for **the GameFiles (It will get download via the Launcher)**.

3 - Extract the **Release.zip** into the Launcher Folder, and run as Administrator the **GameLauncher.exe** . 
----> Note : It may ask you to download some additional componements, you should let it and accept that, because some important things wasn't installed on you pc.

4 -Once you choose the server, and the launcher will appear on it complete form in front of you. Go on the launcher settings (_It looks like a gear icon)_, then, look for ** Change GameFiles Path**. This step will let you change the GameFiles directory, Make sure you choose **The GameFiles folder** that you have created it on **X:\SBRW**.  Click on save to save your changes, and restart the Launcher.

I guess, this is the right solution for you. Inform me if it worked for you.
Kind Regards,
Mr.Elite.

**Comment by fco131** [comment]
I dont get why I need to directly install this into my c : drive  it just seems like it can cause more damage if a un experience user  accidently adds it to the wrong drive like idk...... windows main folder
