### ISSUE TITLE
Can not play NFSW on my computer after update 2-7-2021

### ISSUE THREAD

**Issue by TitaniumRacer** [SoapboxRaceWorld/GameLauncher_NFSW#122]
- **Launcher Version:** 
- **Operating system:** 
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):**

**Comment by TitaniumRacer** [comment]
Soapbox Race world - Ver v2.1.7.1  -- Windows 7 pro - No AV - windows firewall only 
Wont install new launcher. I get a warning saying : Please choose a different directory for game launcher. Special folders such as:Downloads, Documents, Desktop, videos, Music OneDrive , or any Type of user folder, are Disadvided. 
(A warning box with a red X.) Tried using a big enough USB drive but it is FAT32 and it needs NTFS. Wont let me put it on hard drive.(?) It worked fine before the update. HOW am I supposed to play the game? PLEASE help me. Where do I install it so it will work?

**Comment by x-Ghosts** [comment]
Hello @TitaniumRacer  !

The message that you have received recently on the launcher refers to the Launcher files location - directory. Well, the launcher now will not accept the following directories :

(X is the drive that has the OS like C or D, if this last is a primary drive).

X:\Program Files
X:\Program Files (x86)
X:\Users_(ActualAccountonyourpc)_\Downloads
X:\Users_(ActualAccountonyourpc)_\Documents
X:\Users_(ActualAccountonyourpc)_\Desktop
X:\Users_(ActualAccountonyourpc)_\Video
X:\Users_(ActualAccountonyourpc)_\Music
X:\Users_(ActualAccountonyourpc)_\OneDrive
.....
That's why we recommend first to :
1 - Create first of all a folder on your actual drive that has the OS. If *C:* is your actual Drive that contain the OS, create a folder called by : SBRW or SoapBox Race World. Make sure it looks like the image on this link : https://imgur.com/a/mXgccEu.

2 - On that SBRW Folder that you have just created, make sure you create 2 other sub-folders : one goes for the Launcher Files (that you will extract it via the Release.zip) and the other goes for the GameFiles (It will get download via the Launcher).

3 - Extract the Release.zip into the Launcher Folder, and run as Administrator the GameLauncher.exe .
----> Note : It may ask you to download some additional componements, you should let it and accept that, because some important things wasn't installed on you pc.

4 -Once you choose the server, and the launcher will appear on it complete form in front of you. Go on the launcher settings (It looks like a gear icon), then, look for ** Change GameFiles Path**. This step will let you change the GameFiles directory, Make sure you choose The GameFiles folder that you have created it on X:\SBRW. Click on save to save your changes, and restart the Launcher.

I guess, this is the right solution for you. Inform me if it worked for you.
Kind Regards,
Mr.Elite.

**Comment by TitaniumRacer** [comment]
It DID Work ! :-)  Thank you very much.
    On Monday, February 8, 2021, 01:03:29 PM PST, Mr.Elite <notifications@github.com> wrote:  
 
 


Hello @TitaniumRacer !

The message that you have received recently on the launcher refers to the Launcher files location - directory. Well, the launcher now will not accept the following directories :

(X is the drive that has the OS like C or D, if this last is a primary drive).

X:\Program Files
X:\Program Files (x86)
X:\Users_(ActualAccountonyourpc)\Downloads
X:\Users(ActualAccountonyourpc)\Documents
X:\Users(ActualAccountonyourpc)\Desktop
X:\Users(ActualAccountonyourpc)\Video
X:\Users(ActualAccountonyourpc)\Music
X:\Users(ActualAccountonyourpc)_\OneDrive
.....
That's why we recommend first to :
1 - Create first of all a folder on your actual drive that has the OS. If C: is your actual Drive that contain the OS, create a folder called by : SBRW or SoapBox Race World. Make sure it looks like the image on this link : https://imgur.com/a/mXgccEu.

2 - On that SBRW Folder that you have just created, make sure you create 2 other sub-folders : one goes for the Launcher Files (that you will extract it via the Release.zip) and the other goes for the GameFiles (It will get download via the Launcher).

3 - Extract the Release.zip into the Launcher Folder, and run as Administrator the GameLauncher.exe .
----> Note : It may ask you to download some additional componements, you should let it and accept that, because some important things wasn't installed on you pc.

4 -Once you choose the server, and the launcher will appear on it complete form in front of you. Go on the launcher settings (It looks like a gear icon), then, look for ** Change GameFiles Path**. This step will let you change the GameFiles directory, Make sure you choose The GameFiles folder that you have created it on X:\SBRW. Click on save to save your changes, and restart the Launcher.

I guess, this is the right solution for you. Inform me if it worked for you.
Kind Regards,
Mr.Elite.

**Comment by x-Ghosts** [comment]
Have fun ! @TitaniumRacer 
Feel free to report any issue you encounter here, and i'll try my best to find a solution for it. 

See ya on the streets !
