### ISSUE TITLE
Hi my game freeze.How to fix it?

### ISSUE THREAD

**Issue by ken640** [SoapboxRaceWorld/GameLauncher_NFSW#124]
- **Launcher Version:** 
- **Operating system:** 
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):**

**Comment by x-Ghosts** [comment]
Hello @ken640 !

Can you try to detail more, exactly when and where it does freezes ?

Once you detail the answer, I may find a solution for you.

Kind Regards,
Mr.Elite

**Comment by ken640** [comment]
I dont know how to explained,but i think i got more big error happening now.Since i  updated new need for speed launcher,my files always shortcuts.I dont want reinstal my game because it took long hours to finish downloading.What should i do?

**Comment by x-Ghosts** [comment]
Hello @ken640 !

Try to restart the download system from the beggining, but by following the following format.

1 - Create first of all a folder on your actual drive that has the OS. If C: is your actual Drive that contain the OS, create a folder called by : SBRW or SoapBox Race World. Make sure it looks like the image on this link : https://imgur.com/a/mXgccEu.

2 - On that SBRW Folder that you have just created, make sure you create 2 other sub-folders : one goes for the Launcher Files (that you will extract it via the Release.zip) and the other goes for the GameFiles (It will get download via the Launcher).

3 - Extract the Release.zip into the Launcher Folder, and run as Administrator the GameLauncher.exe .
----> Note : It may ask you to download some additional componements, you should let it and accept that, because some important things wasn't installed on you pc.

4 -Once you choose the server, and the launcher will appear on it complete form in front of you. Go on the launcher settings (It looks like a gear icon), then, look for ** Change GameFiles Path**. This step will let you change the GameFiles directory, Make sure you choose The GameFiles folder that you have created it on X:\SBRW. Click on save to save your changes, and restart the Launcher.

I guess, this is the right solution for you. Inform me if it worked for you.
Kind Regards,
Mr.Elite
