### ISSUE TITLE
"Choose a different directory"

### ISSUE THREAD

**Issue by EXDYahir** [SoapboxRaceWorld/GameLauncher_NFSW#129]
- **Launcher Version:** Release_2.1.7.2
- **Operating system:** Win 7
- **Antivirus/Firewall (if any):** No/Yes
- **Wine/Mono Version (if any):** 

- I still got the same issue with the other version
- If I can't put the game in Program Files or another folder where the f**k can I put it??? A Flash Drive???

**Comment by Andromedusa1** [comment]
you just have to put the launcher in a source folder example: C:\

**Comment by x-Ghosts** [comment]
Hello @EXDYahir   !

The message that you have received recently on the launcher refers to the Launcher files location - directory. Well, the launcher now will not accept the following directories :

(X is the drive that has the OS like C or D, if this last is a primary drive).

X:\Program Files
X:\Program Files (x86)
X:\Users_(ActualAccountonyourpc)_\Downloads
X:\Users_(ActualAccountonyourpc)_\Documents
X:\Users_(ActualAccountonyourpc)_\Desktop
X:\Users_(ActualAccountonyourpc)_\Video
X:\Users_(ActualAccountonyourpc)_\Music
X:\Users_(ActualAccountonyourpc)_\OneDrive
.....
That's why we recommend first to :
1 - Create first of all a folder on your actual drive that has the OS. If *C:* is your actual Drive that contain the OS, create a folder called by : SBRW or SoapBox Race World. Make sure it looks like the image on this link : https://imgur.com/a/mXgccEu.

2 - On that SBRW Folder that you have just created, make sure you create 2 other sub-folders : one goes for the Launcher Files (that you will extract it via the Release.zip) and the other goes for the GameFiles (It will get download via the Launcher).

3 - Extract the Release.zip into the Launcher Folder, and run as Administrator the GameLauncher.exe .
----> Note : It may ask you to download some additional componements, you should let it and accept that, because some important things wasn't installed on you pc.

4 -Once you choose the server, and the launcher will appear on it complete form in front of you. Go on the launcher settings (It looks like a gear icon), then, look for ** Change GameFiles Path**. This step will let you change the GameFiles directory, Make sure you choose The GameFiles folder that you have created it on X:\SBRW. Click on save to save your changes, and restart the Launcher.

I guess, this is the right solution for you. Inform me if it worked for you.
Kind Regards,
Mr.Elite.
