### ISSUE TITLE
NFS World opens when I click on play game but then it crashes. Please fix

### ISSUE THREAD

**Issue by reilymoises2321** [SoapboxRaceWorld/GameLauncher_NFSW#134]
- **Launcher Version:** 2.1.7.3
- **Operating system:** Windows 10
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):** 
- 
![0C319A49-50F3-4D94-AF17-8A675D239D66](https://user-images.githubusercontent.com/79724944/109359235-18e1c500-7853-11eb-8deb-07f12741fa10.jpeg)

**Comment by x-Ghosts** [comment]
Hello @reilymoises2321 !

This issue shows up when something is messed up with your game, caused by : 
- A bad Gamefiles Installation
- Corrupted Gamefiles
- Antivirus Presence
- Non Updated OS - Check Windows Update
- Non updated GPU Drivers
etc ...

We ask in this case, to send us this txt file here (below my message) or on our Official Discord Server : SBRW Server invite **https://discord.gg/hsHvBdKjyq** and we can help you with the issue more there.

Kind Regards,

- Nero-h

**Comment by reilymoises2321** [comment]
This is the file error I get:
[SBRCrashDump_CL0_2021.02.27_04.44.10.txt](https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/files/6053754/SBRCrashDump_CL0_2021.02.27_04.44.10.txt)

**Comment by x-Ghosts** [comment]
Hello @reilymoises2321 !

Our actual launcher developpers managed to find this type of issue on the txt that you sent before : 

*Unhandled exception at 0x00F99065 in nfsw.exe **(+0xc9065)**: 0xC0000005: Access violation reading location 0x00000000.*

We recommend you to get the latest version of the Launcher, by updating via your launcher (When you open it, a small window will pop up and asks you if you desire to update the launcher to 2.1.7.5 - Click Accept).

Or, download it from here : **https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/releases/download/2.1.7.5/Release_2.1.7.5.zip**

Inform us if your issue has been fixed or not, by mentioning it here.

Kind Regards,
- Nero-h

**Comment by reilymoises2321** [comment]
The game now works, I had to delete all the files and re-download and now everything works good with the new update... Thank you so much for the help!

**Comment by x-Ghosts** [comment]
Hello @reilymoises2321 !

I'm glad that your game work fine now. Time to have fun in game ! And see you on the streets too !

Kind Regards,
- Nero-h
