### ISSUE TITLE
Modnet is causing launcher to crash.

### ISSUE THREAD

**Issue by Catzy44** [SoapboxRaceWorld/GameLauncher_NFSW#14]
- **Launcher Version:** 2.0.3.9
- **Operating system:** Windows 7 Pro, x64
- **Antivirus/Firewall (if any):**  Avast Free
- **Wine/Mono Version (if any):** -/-

My launcher is always crashing when modnet is not disabled.

After closing message i got "Stack buffer overflow (0xC0000409)"

Here`s info from crash message (Sorry for language, i have PL version of windows):
Podpis problemu:
  Nazwa zdarzenia problemu:	BEX
  Nazwa aplikacji:	nfsw.exe
  Wersja aplikacji:	1.0.0.1613
  Sygnatura czasowa aplikacji:	55529d64
  Nazwa modułu z błędem:	ModManager.asi
  Wersja modułu z błędem:	0.0.0.0
  Sygnatura czasowa modułu z błędem:	5b60c0df
  Przesunięcie wyjątku:	00002fbc
  Kod wyjątku:	c0000409
  Dane wyjątku:	00000000
  Wersja systemu operacyjnego:	6.1.7601.2.1.0.256.48
  Identyfikator ustawień regionalnych:	1045
  Dodatkowe informacje 1:	98de
  Dodatkowe informacje 2:	98dec98d4d3d837616a5439c4f2984af
  Dodatkowe informacje 3:	4a3c
  Dodatkowe informacje 4:	4a3c3afdb8d1f2438a9570ed6dc3bdad

**Comment by Zacam** [comment]
ModManager.asi problems can be caused by Microsoft Visual Studio C++ Runtimes (usually either 2010 or 2015). Make sure both x86/32bit and x64/64bit versions are properly installed; either by doing a "Repair" with an installer for them, or by Uninstalling any major.minor versions and doing a clean install of the latest version available. (Links to all latest currently supported versions are here: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads )

**Comment by Zacam** [comment]
Through Discord conversation:
2010 is current. 2015 was not installed, but 2017 was.
Combo pack for 2015/2017/2019 was installed to replace 2017. Same Error.
Working ModManager.asi was provided, user local one (from fresh download) was only 59.5 KB; working file is 112 KB.
