### ISSUE TITLE
Game just don't want to lauch 

### ISSUE THREAD

**Issue by SpiritLeRenard** [SoapboxRaceWorld/GameLauncher_NFSW#164]
- **Launcher Version:** 2.1.7.8-1
- **Operating system:** Windows 7 
- **Antivirus/Firewall (if any):** Yes (bitdefender)/no 
- **Wine/Mono Version (if any):** 

I have downloaded the latest version, followed the instructions with the folder and the two sub folder, but the game just doesn't want to lauch and give me an infinity "soapbox race world" without loading any launcher

**Comment by DavidCarbon** [comment]
For Bitdefender, you will need to exclude the Folder for the Launcher and Game since Bitdefender removes files that are necessary for launcher and game to work correctly.
You can use this as a reference (Note that there is no directions so you will have to rely on images only): https://imgur.com/a/BTuJR2j
