### ISSUE TITLE
Probably missing some breakpoint after the cases, CheckFolder and others... Am i wrong?

### ISSUE THREAD

**Issue by SubCoderHUN** [SoapboxRaceWorld/GameLauncher_NFSW#166]
//Probably missing some breakpoint
https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/blob/9734eff2a740d1c536948ab49f01ddc9dc63d83d/GameLauncher/App/Classes/LauncherCore/Global/FunctionStatus.cs#L260
// There is no point to use this, why is it here?
https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/blob/9734eff2a740d1c536948ab49f01ddc9dc63d83d/GameLauncher/App/Classes/LauncherCore/Global/FunctionStatus.cs#L124
Instead use this, if the point was to check the folder name. But now, i have no clue wtf is this.

        static bool IsValidFolder(string FolderName)
        {
            Regex containsABadCharacter = new Regex("["+ Regex.Escape(new string(Path.GetInvalidPathChars())) + "]");
            if (containsABadCharacter.IsMatch(FolderName)) 
            { return false; };

            //checks for UNC, drive-path format, etc...
            return true;
        }
                if (!IsValidFolder(FileSettingsSave.GameInstallation))
                {
                    String constructMsg = null;
                    Directory.CreateDirectory("Game Files");
                    constructMsg += "Using this characters as folder name for Game Files is not allowed.\nThe following list are NOT allowed:\n\n";
                    constructMsg += "• (^(PRN|AUX|NUL|CON|COM[1-9]|LPT[1-9]|(\\.+)$)(\\..*)?$)|(([\\x00-\\x1f\\\\?*:\";‌​|/<>])+)|([\\. ]+)\n";
                    constructMsg += "Instead, we will install the NFSW Game at "+AppDomain.CurrentDomain.BaseDirectory+"\\Game Files\n";

                    MessageBox.Show(null, constructMsg, "GameLauncher", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    Log.Error("LAUNCHER: Installing NFSW in a Restricted Location is not allowed.");
                    FileSettingsSave.GameInstallation = AppDomain.CurrentDomain.BaseDirectory + "\\Game Files";
                }
//What is this mess in this file?
https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/blob/9734eff2a740d1c536948ab49f01ddc9dc63d83d/GameLauncher/App/Classes/LauncherCore/Downloader/Downloader.cs#L255
//There is no point to use 'try' in a 'try' function.
https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/blob/9734eff2a740d1c536948ab49f01ddc9dc63d83d/GameLauncher/App/Classes/LauncherCore/Lists/ServerListUpdater.cs#L26

**Comment by DavidCarbon** [comment]
Hello. Thanks for the Report and Code Sample Suggestion.
- For FunctionStatus.CheckFolder is used in different parts of the launcher not just one sub section of the launcher, However I will keep note of it in future revisions of the launcher. 
- For the Folder Name Check, in older Launcher Builds the separation of each switch break comparison had their own dedicated message box. But was later changed to a single message box.
  - As for the Your Code Sample, the function "IsValidFolder" will check for bad characters, this has been explored and the both divisions (Server and Launcher) have come to a mutual agreement that UniCode characters can be used just not for the Game File Path
- For the Downloader.cs#L255 this goes through the xml file from the CDN. If you are wondering is there a better solution or a possible rewrite, it possible but will require lots of Beta testers (Something were are lacking, since this project is done on people's spare time)
- For ServerListUpdater.cs#L26 while the try-catch within another try-catch may seem odd on Lines 30-33 shows the Deserialization of JSON file. So if the Server is offline or Client Side is unable to connect to it, this will trigger the next URL to be loaded in

**Comment by SubCoderHUN** [comment]
Hello there. Thanks for your answer, I appreciate.
I'll read the source code deeper in the near future, and if I find a better solution for certain features, I'll report to you.

**Good luck for the future!**
