### ISSUE TITLE
NFSW.EXE was killed by task manager 

### ISSUE THREAD

**Issue by Spartan767** [SoapboxRaceWorld/GameLauncher_NFSW#173]
- **Launcher: 2.1.7.8** 
- **Operating System: windows 10** 
- **Antivirus/Firewall (if any):windows defender 
![nfsworld error](https://user-images.githubusercontent.com/84758644/119435473-360a2080-bce8-11eb-9014-0cc6a56ca8f6.jpeg)
** 
- **Wine/Mono Version (if any):** 
 Ive Tried everything sigh

**Comment by x-Ghosts** [comment]
Hello @Spartan767 ! 

Can you explain what happened, exactly to that issue. I mean, does your game crash at the first loading, when you just open the game, or you were playing for a long time, then your game got closed ... ? 

We need you that you provide more details, in order to give you the right support details. 

Thanks for reading, and apologize for late replies.

**Comment by Shirooh** [comment]
Me too, when i iniciate the game, in first loading he crash... i'm using the windows 11.

**Comment by Sixcat6** [comment]
Yeah, I also have the same problem
I think i just have to send these two files it says:
![Capture](https://user-images.githubusercontent.com/118140926/201550486-4aa8b5e7-0e28-4d0c-9289-9a1bd655426f.PNG)
That is a capture of the error screen
Here are the files:
[SBRCrashDump_CL0_2022.11.13_22.51.43.txt](https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/files/9998511/SBRCrashDump_CL0_2022.11.13_22.51.43.txt)
I think I couldn't send the DMP file, since it's not supported, but theres the error screen and the text file

**Comment by gabimalmeida** [comment]
managed to solve?

**Comment by Sixcat6** [comment]
Nope

**Comment by Zildrik** [comment]
![22](https://user-images.githubusercontent.com/120746278/208164297-797cecf1-a738-4852-93bc-034650ba8d71.png)

**Comment by Zildrik** [comment]
help m

**Comment by maggo3501** [comment]
got answer on reddit: Validate files manually. It missses a bunch by default.
(u do this in the launcher, options)
