### ISSUE TITLE
Game Crash: Access Violation (0xC0000005)

### ISSUE THREAD

**Issue by TakuyaSama** [SoapboxRaceWorld/GameLauncher_NFSW#202]
- **Launcher Version: 2.1.9.0002**
- **Operating system: Linux**
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any): lutris-fshack-6.14-4-x86_64 (the one which cames with Lutris)**
#22 
I'm experiencing the same issue that's described here, but on Linux, after an update of a few packages yesterday, the game starts to load in the loading screen, it freezes and shows the same error message @Hakunek described.
I tried the file validation tool, it downloaded 25 files that it detected were issues with, but same result, I re run it and 0 files found, but still the same.
I'm suspecting that some package that got updated yesterday are the one which is causing this.

**Comment by CosmicFusion** [comment]
* Environment info : 
- Wine : lutris-fshack-5.14
- Distro : Pop!OS 22.04 LTS
- WINEARCH : x64
- kernel : 5.17.5-76051705-generic
- Using Lutris/Bottles : [no] : Nah i use the command-line , no need for a stinky GUI

Same everything :

* Same crash code 

* Same behavior

* Same amount of "corrupted" files (25)


Steps to re-produce (at least on my system)

* Use Linux

* Switch the server you want to play on

* Now all servers are broken and you can't enter games .

**Comment by CosmicFusion** [comment]
Fixed it,  ~~use this [wine](https://github.com/SoapboxRaceWorld/Wine-NFSW) build it's made specifically by the soapbox team for linux , it is an ancient one though so you need gallium nine or a really old dxvk build that still supports legacy wine , because the wined3d in this wine build so terrible , also for some bizarre reason horizon doesn't work here .~~ Use the official wine build not a custom one , that should fix it .
