### ISSUE TITLE
A critical error in the game process has occurred...

### ISSUE THREAD

**Issue by SRSWORD** [SoapboxRaceWorld/GameLauncher_NFSW#215]
- **Launcher Version:** 
- **Operating system:** 
![Sem título](https://user-images.githubusercontent.com/117130936/199137528-038c9b97-f5b8-498a-bafb-ce45e828c15b.png)

- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):** 

![Sem tIítulo](https://user-images.githubusercontent.com/117130936/199137635-faf22976-5124-42ea-89dd-363b956c4b51.png)

**Comment by Gaston747** [comment]
Hola, lo has podido resolver?

**Comment by x-Ghosts** [comment]
Hello @SRSWORD 

In order to check your issue linked to you description, you need to link the files that is mentionned on the error window **SBRCrashDump...txt** to here. (You can find these on your gamefiles, at the bottom). In that txt, all details will be mentioned in order to solve your issue linked to the problem.

**Comment by Steb28** [comment]
Hello. I had this issue and I just created the account to see if you could fix it, please. Here is the crash dump.
[SBRCrashDump_CL0_2022.11.10_01.02.56.txt](https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/files/9993134/SBRCrashDump_CL0_2022.11.10_01.02.56.txt)

**Comment by Zacam** [comment]
"Verify Game Files" in the Settings Screen (Gear button, top right) and try again.
