### ISSUE TITLE
Erreur critique 

### ISSUE THREAD

**Issue by Fractal390** [SoapboxRaceWorld/GameLauncher_NFSW#226]
- **Launcher Version:** 
- Release_2.2.0.2
- **Operating system:** 
- Windows 11
- **Antivirus/Firewall (if any):** 
- Kaspersky
- **Wine/Mono Version (if any):** 
- 

[SBRCrashDump_CL0_2022.12.25_19.06.24.txt](https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/files/10300523/SBRCrashDump_CL0_2022.12.25_19.06.24.txt)

**Comment by MVarelDE** [comment]
did u crash while loggin in? because i have the same problem it said send it to developer

**Comment by Zacam** [comment]
"Verify Game Files" in the Launchers Settings Screen (Gear button, top right)

If it still happens and/or Verify has found no issues to repair, then I'd suggest creating an Exclusion/Exception in Kaspersky to "Ignore" the Game Files folder and the Launcher folder so that it stops interfering with both.
