### ISSUE TITLE
So much lag (Apex Server)

### ISSUE THREAD

**Issue by SparkYy132** [SoapboxRaceWorld/GameLauncher_NFSW#38]
Why is there so much lag on the apex server 
Ex:You want to enter Car Dealer and you click it,then you can go to drink  a coffee 'til it loads...

**Comment by VoidSlayer** [comment]
I have the same lag, when you want to do a transaction, do an event or even collect gems while freeroaming you need to wait too much. This happens when there are 300+ players. In the mornings when there are only 100ish players the game it's very enjoyable and there aren't bugs due to the connection.

**Comment by metonator** [comment]
Too many players at same time.
