### ISSUE TITLE
Can't start the game

### ISSUE THREAD

**Issue by becakmumbul** [SoapboxRaceWorld/GameLauncher_NFSW#43]
Crash and can't start the game

[SBRCrashDump_CL0_2020.05.12_02.28.38.txt](https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/files/4613084/SBRCrashDump_CL0_2020.05.12_02.28.38.txt)

**Comment by Cameron-Naidoo** [comment]
Just got this issue after a first-time install today on Windows 7. After some research, found that it can sometimes be related to faulty cracks.

I deleted all the files and used a fresh launcher again but selected NightRiderz instead of WorldUnited to download the files from and it's working perfectly.
