### ISSUE TITLE
Game Error at login - Out of Memory?

### ISSUE THREAD

**Issue by Vexevin** [SoapboxRaceWorld/GameLauncher_NFSW#57]
- **Launcher Version:** v2.1.2.6Build-78094cf
- **Operating system:** W10 Home
- **Antivirus/Firewall (if any):** Kaspersky
- **Wine/Mono Version (if any):** 

![image](https://user-images.githubusercontent.com/67076556/84950258-da80ed00-b0ab-11ea-8fb3-cbd621e29b02.png)

**Comment by Zacam** [comment]
That looks like a communications disruption fetching files from somewhere.
Could be either ISP (internet Service Provider or DNS Related); wireless access point (if on Wireless), or Firewall/Antivirus.

Specifically, Kapersky at present does NOT like NFSW at all; though there is reportedly a way to convince it to "play nice" rather than having to completely exit Kapersky entirely while playing:

(make sure status is set to Active on the final window)
![Kapersky](https://user-images.githubusercontent.com/2995385/85011309-31231100-b116-11ea-9b52-429066cd2d00.png)
