### ISSUE TITLE
missing translatable strings

### ISSUE THREAD

**Issue by GitMensch** [SoapboxRaceWorld/GameLauncher_NFSW#60]
Some strings are currently not translatable (especially the Updater, and error messages like "do you want to restart") and it seems part of the main gui like "Don't have an account" are even images.

This FR is about:

* replacing all (or this single?) image by a button with a translatable text
* changing all messages to use translatable texts

*Maybe* the way the translatable messages are stored/received should be changed, too. The most common ways seems to be language resource files (hopefully they don't need to be compiled to a .dll) or gettext.

**Comment by metonator** [comment]
I know about this, this is intentional.

**Comment by GitMensch** [comment]
?!? Can you explain this a bit, please?

**Comment by metonator** [comment]
Not all text can be translatable because of:
- "lack of buttons that support HTML or any other <bold> system" [This won't be fixed, new "UI" uses something better than "static image from photoshop"]
- continiuous reading from settings.ini file (limited that to just one file, coz was easiest thing i could do, rest is just useless translation) [Can be fixed]
