### ISSUE TITLE
I cannot open the again 

### ISSUE THREAD

**Issue by jsebastian1294** [SoapboxRaceWorld/GameLauncher_NFSW#62]
- **Launcher Version:1.0.0.1613
- **Operating system:windows 10 64bits
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):** 

**Description of issue:**
I had got to resintall the game because I once close it, it didn't start again and now is happening the same the game was closed by an error and now it doesn't restart again. 
Error description goes here
```

**JIT Error (if any)**
```
Please embed it inside code tag. Otherwise, delete this line or just type "none"
none

**Comment by metonator** [comment]
check `Settings.ini` file and look @ `LocationX` and `LocationY` property. if is -32000, change it to 0

**Comment by GitMensch** [comment]
@metonator sounds like something the application could do on startup (if this is a known issue to you), too

**Comment by metonator** [comment]
in fact it is, but can fail because of "permission" sometimes

**Comment by metonator** [comment]
https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/blob/master/GameLauncher/App/Form1.cs#L327

**Comment by metonator** [comment]
or i did it wrong 🤔

**Comment by GitMensch** [comment]
Minimal code-review of the referenced source line and its context (speaking with never inspected the actual run) follows...

The part that looks strange in this code is that you use the primary screen size - are you sure that the window is on the primary screen? Which screen is used by `centerScreen`?

Can you log the branch that goes into this fix and catch / log exceptions that may occur on repositioning?

In general I think it would be better to check x and y separate, set newX/newY to 0 if these are below the limit (otherwise to currentX/Y) and to currentScreen.Bounds - this.width/height if they are over the limit (pseudo-code). The reposition the screen to NewX/NewY.

@jsebastian1294 does this happen with a multi-monitor setup?

**Comment by metonator** [comment]
```csharp
        public static void centerScreen(Form form) {
            form.StartPosition = FormStartPosition.Manual;
            form.Top = (Screen.PrimaryScreen.Bounds.Height - form.Height) / 2;
            form.Left = (Screen.PrimaryScreen.Bounds.Width - form.Width) / 2;
        }
``` 

i think i have to fix that ASAP

**Comment by normally12** [comment]
I have the same issue when i close the launcher then the GameLauncher.exe disappear from my folder and i cant reopen game what can i do to fix that?

**Comment by GitMensch** [comment]
@normally12 this is a **completely** unrelated "feature" of your security suite (you may fix it there, for example with uploading a false-positive, set an exclusion, ...).
This issue was about the application *window* that isn't correctly positioned, not the executable.
